# Generated by Django 4.2.16 on 2024-11-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
